version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawler
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawler
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_DSN: crawler:crawler@tcp(db:3306)/crawler?parseTime=true
      PORT: 8080
      AUTH_TOKEN: secret-token
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  dbdata:
